name: test

on: push

env:
  DOCKER_COMPOSE_VERSION: 19.03.0

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d

      - name: Docker Compose
        run: docker-compose run fhir npm test